/** @format */

export const GAME_LIST = {
  webzin: [
    {
      name: "The Binding of Isaac : Rebirth",
      genre: "액션,RPG,탑다운,슈팅",
      playTime: 5,
      localization: true,
      path: "../img/webzin/The Binding of Isaac - Rebirth.webp",
    },
    {
      name: "Furi",
      genre: "액션,보스 러쉬",
      playTime: 5.5,
      localization: true,
      path: "../img/webzin/Furi.webp",
    },
    {
      name: "Braid",
      genre: "플랫폼,퍼즐",
      playTime: 5,
      localization: true,
      path: "../img/webzin/Braid.webp",
    },
    {
      name: "Superhot",
      genre: "1인칭,슈팅,퍼즐",
      playTime: 2.5,
      localization: true,
      path: "../img/webzin/Superhot.webp",
    },
    {
      name: "Rise & Shine",
      genre: "액션,어드벤처,스크롤",
      playTime: 2.5,
      localization: true,
      path: "../img/webzin/Rise & Shine.webp",
    },
    {
      name: "Hotline Miami",
      genre: "탑다운,액션,슈터",
      playTime: 5,
      localization: true,
      path: "../img/webzin/Hotline Miami.webp",
    },
    {
      name: "To the Moon",
      genre: "어드벤처,RPG",
      playTime: 4,
      localization: true,
      path: "../img/webzin/To the Moon.webp",
    },
    {
      name: "Firewatch",
      genre: "어드벤처,1인칭",
      playTime: 4,
      localization: true,
      path: "../img/webzin/Firewatch.webp",
    },
    {
      name: "Nidhogg",
      genre: "대전",
      playTime: 1,
      localization: false,
      path: "../img/webzin/Nidhogg.webp",
    },
    {
      name: "The Stanley Parable",
      genre: "1인칭,어드벤처",
      playTime: 1.5,
      localization: true,
      path: "../img/webzin/The Stanley Parable.webp",
    },
    {
      name: "Outlast",
      genre: "1인칭,호러",
      playTime: 5,
      localization: true,
      path: "../img/webzin/Outlast.webp",
    },
    {
      name: "Papers,Please",
      genre: "텍스트,퍼즐,시뮬레이션",
      playTime: 5,
      localization: true,
      path: "../img/webzin/Papers,Please.webp",
    },
    {
      name: "Limbo",
      genre: "플랫폼,퍼즐,스크롤",
      playTime: 3,
      localization: true,
      path: "../img/webzin/Limbo.webp",
    },
    {
      name: "Into the Breach",
      genre: "턴제,RPG",
      playTime: 5.5,
      localization: true,
      path: "../img/webzin/Into the Breach.webp",
    },
    {
      name: "Devil Daggers",
      genre: "1인칭,액션,슈팅,호러",
      playTime: 5.5,
      localization: false,
      path: "../img/webzin/Devil Daggers.webp",
    },
    {
      name: "Pony Island",
      genre: "퍼즐",
      playTime: 2.5,
      localization: true,
      path: "../img/webzin/Pony Island.webp",
    },
    {
      name: "Doki Doki Literature Club",
      genre: "텍스트,비주얼 노벨",
      playTime: 4,
      localization: true,
      path: "../img/webzin/Doki Doki Literature Club.webp",
    },
    {
      name: "What Remains of Edith Finch",
      genre: "어드벤처",
      playTime: 2,
      localization: true,
      path: "../img/webzin/What Remains of Edith Finch.webp",
    },
  ],
  editorsPicks: [
    {
      name: "Deemo -Reborn-",
      genre: "리듬,어드벤처",
      count_apps: 0,
      count_play: 100000,
      description: "",
      path: "../img/editorpicks/deemo.webp",
    },
    {
      name: "쥐돌이 버스터즈",
      genre: "어드벤처",
      count_apps: 0,
      count_play: 100000,
      description: "",
      path: "../img/editorpicks/mouse busters.webp",
    },
    {
      name: "오리DUCK후",
      genre: "캐주얼,방치",
      count_apps: 0,
      count_play: 1000000,
      description: "",
      path: "../img/editorpicks/duckhu.webp",
    },
    {
      name: "츠키의 모험",
      genre: "어드벤처,방치",
      count_apps: 0,
      count_play: 1000000,
      description: "",
      path: "../img/editorpicks/tsuki.webp",
    },
    {
      name: "크랩 전쟁",
      genre: "어드벤처,스크롤,슈팅",
      count_apps: 0,
      count_play: 5000000,
      description: "",
      path: "../img/editorpicks/crab war.webp",
    },
    {
      name: "Beholder",
      genre: "어드벤처",
      count_apps: 0,
      count_play: 100000,
      description: "",
      path: "../img/editorpicks/beholder.webp",
    },
    {
      name: "Like A Dino!",
      genre: "리듬",
      count_apps: 0,
      count_play: 10000000,
      description: "",
      path: "../img/editorpicks/like a dino.webp",
    },
    {
      name: "팬텀 로즈 스칼렛",
      genre: "로그라이크,카드,어드벤처",
      count_apps: 0,
      count_play: 500000,
      description: "",
      path: "../img/editorpicks/phantomrosescalret.webp",
    },
    {
      name: "Dadish 2",
      genre: "플랫폼,액션",
      count_apps: 0,
      count_play: 100000,
      description: "",
      path: "../img/editorpicks/dadish2.webp",
    },
    {
      name: "pink (game)",
      genre: "퍼즐",
      count_apps: 0,
      count_play: 100000,
      description: "",
      path: "../img/editorpicks/pink.webp",
    },
    {
      name: "고양이와 스프",
      genre: "방치형,시뮬레이션",
      count_apps: 0,
      count_play: 1000000,
      description: "구글 플레이 인디게임 페스티벌 수상작(TOP 3)",
      path: "../img/editorpicks/cat&soup.webp",
    },
  ],
  intwohundreds: [
    {
      name: "창술사 키우기",
      rank: [null, null, null, null, 75],
      genre: "방치형",
      path: "../img/intwohundreds/lance.webp",
    },
    {
      name: "사신키우기 온라인",
      rank: [56, 72, 71, 71, 76],
      genre: "방치형",
      path: "../img/intwohundreds/reaper.webp",
    },
    {
      name: "슬레이어 키우기",
      rank: [130, 200, 34, 57, 92],
      genre: "방치형",
      path: "../img/intwohundreds/slayer.webp",
    },
    {
      name: "마피아42",
      rank: [100, 108, 115, 73, 112],
      genre: "전략, 시뮬레이션",
      path: "../img/intwohundreds/mafia.webp",
    },
    {
      name: "임모탈 키우기",
      rank: [null, null, null, 114, 144],
      genre: "방치형",
      path: "../img/intwohundreds/immotal.webp",
    },
    {
      name: "좀비 고등학교",
      rank: [173, 151, 133, 148, 181],
      genre: "액션",
      path: "../img/intwohundreds/zombie.webp",
    },
  ],
};
